name: Deploy Portfolio API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get GitHub Runner IP
      run: curl -s https://ifconfig.me

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Using Appleboy SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/smc-portfolio-api
          git pull origin main
          npm install
          pm2 restart server.js

